version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Europe/Amsterdam
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - appmkt

  frontend:
    build:
      context: ./app
    ports:
      - "3000:3000"
    networks:
      - appmkt

  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DB_HOST: db
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    networks:
      - appmkt

networks:
  appmkt:
    driver: bridge
